live_config_reload = true

[window]
blur = true
padding = { x = 16, y = 16 }
#decorations = "Buttonless"
startup_mode = "Maximized"

[font]
normal = { family = "MesloLGS NF", style = "Regular" }
size = 16 

[env]
TERM = "alacritty"

